const ACTION_TYPES = {
    INITIALISE_STATE: '@@INIT',
    CHILD_CLOSED: 'CLOSE',
    DRAG_START: 'DRAG_START',
    DRAG_END: 'DRAG_END',
    REOPEN_WINDOW: 'REOPEN_WINDOW'
};

module.exports = ACTION_TYPES;
